version: '3.2'

services: 
  frontend:
    image: frontend-react
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
    # [인증서 파일 저장 경로]:/var/www/html
    # volumes:
    #   - /home/ubuntu/docker-volume/ssl:/var/www/html
    container_name: "frontend"